### ISSUE TITLE
Docker compose file version

### ISSUE THREAD

**Issue by tpanza** [UCB-w261/w261-environment#17]
Please reconcile this apparent conflict (v2 or v3??) ...

From README.md:

```
version: '3'
services:
  quickstart.cloudera:
    image: w261/w261-environment:latest
    hostname: docker.w261
    privileged: true
```

> version: this item says use **v2** syntax
