### ISSUE TITLE
Add mrjob.conf

### ISSUE THREAD

**Issue by kyleiwaniec** [UCB-w261/w261-environment#9]
Write a conf file in the runner.sh script placing it in the home dir, and containing the following options. Make sure the USERNAME is the loggedin altiscale user (instead of kylehamilton)

This is where mrjob looks for the configuration file:
`~/.mrjob.conf`

```
runners:
  hadoop:
    python_archives: hdfs:///user/kylehamilton/virtualenv/py27.zip#py27
    python_bin: ./py27/bin/python
    cleanup_on_failure: ALL
    cleanup: TMP
```
This will remove the need to specify those options in the command in the notebooks:

```
!python mrjob_versions_test.py \
        -r hadoop one_line.txt \
        # --python-archive={pyArchive} \
        # --python-bin={pyBin} \
        --output-dir={OUTPUT_PATH_1} \
        --no-output
```
## (THIS IS TESTED)
